# Generated by Django 3.2 on 2021-05-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGUOIDUNG',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('TenNguoiDung', models.CharField(max_length=20)),
                ('HoTen', models.CharField(max_length=200)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Quyen', models.IntegerField()),
                ('SDT', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TINHCACH',
            fields=[
                ('IdTinhCach', models.AutoField(primary_key=True, serialize=False)),
                ('Loai', models.IntegerField()),
                ('ChiTiet', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TINHCACH2',
            fields=[
                ('IdTinhCach', models.AutoField(primary_key=True, serialize=False)),
                ('Loai', models.IntegerField()),
                ('ChiTiet', models.CharField(max_length=1000)),
            ],
        ),
    ]
