# Generated by Django 3.2 on 2021-05-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_delete_tinhcach2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='GioiTinh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='NgaySinh',
            field=models.DateTimeField(default='1999-01-01'),
        ),
    ]
