# Generated by Django 3.2 on 2021-05-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210506_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRUONG',
            fields=[
                ('IdTruong', models.AutoField(primary_key=True, serialize=False)),
                ('ChiTiet', models.CharField(max_length=1000)),
            ],
        ),
    ]
