# Generated by Django 3.2 on 2021-05-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_truong'),
    ]

    operations = [
        migrations.AddField(
            model_name='truong',
            name='Point',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='truong',
            name='TenTruong',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='truong',
            name='Votes',
            field=models.IntegerField(default=0),
        ),
    ]
