# Generated by Django 3.2 on 2021-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210506_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truong',
            name='Point',
        ),
        migrations.RemoveField(
            model_name='truong',
            name='Votes',
        ),
        migrations.AlterField(
            model_name='truong',
            name='ChiTiet',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
