# Generated by Django 3.2 on 2021-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210506_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='truong',
            name='ChiTietFull',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
