# Generated by Django 3.2 on 2021-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_truong_chitietfull'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOTE',
            fields=[
                ('IdVote', models.AutoField(primary_key=True, serialize=False)),
                ('IdTruong', models.IntegerField()),
                ('IdUser', models.IntegerField()),
            ],
        ),
    ]
