# Generated by Django 3.2 on 2021-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
